spring.application.name=ecuacion-splib-web-introduction-item-name-key-class
server.port=8080
jp.ecuacion.splib.web.process-result-message.shown-at-the-top=true
jp.ecuacion.splib.web.process-result-message.shown-at-each-item=false
